#!/bin/bash

#depends on: graphicsmagick, i3lock, scrot
# search font name using fc-list | grep name

IMAGE=/tmp/lockscreen.png
TEXT=/tmp/locktext.png
ICON=./lock/lock3.png

rm $TEXT

scrot $IMAGE
convert $IMAGE -scale 10% -scale 1000% -fill black -colorize 25% $IMAGE
[ -f $TEXT ] || { 
    convert -size 3000x70 xc:red -font "/usr/share/fonts/nerd-fonts-complete/otf/3270 Narrow Nerd Font Complete.otf" o -pointsize 48 -fill white -gravity center -annotate +0+0 'This System is now locked.' $TEXT;
    convert $TEXT -alpha set -channel A -evaluate set 70% $TEXT; 
}
convert $IMAGE $TEXT -gravity center -geometry +0+000 -composite $IMAGE
convert $IMAGE $ICON -gravity center -composite -matte $IMAGE
i3lock -u -i $IMAGE

